# Generated by Django 3.1.6 on 2021-03-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='first name')),
                ('lastname', models.CharField(max_length=50, verbose_name='last name')),
                ('role', models.CharField(max_length=50, verbose_name='role')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
                ('bio', models.TextField(verbose_name='bio')),
            ],
        ),
    ]
