# Generated by Django 3.1.6 on 2021-03-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='image',
            field=models.ImageField(default='img.png', upload_to='officer_profiles/'),
        ),
    ]
