# Generated by Django 3.1.6 on 2021-03-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Information', '0002_officer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='event title')),
                ('description', models.TextField(verbose_name='event description')),
                ('start', models.DateTimeField(verbose_name='start time')),
                ('end', models.DateTimeField(verbose_name='end time')),
                ('link', models.URLField(verbose_name='optional link')),
            ],
        ),
        migrations.AlterField(
            model_name='officer',
            name='image',
            field=models.ImageField(upload_to='officer_profiles/'),
        ),
    ]
