# Generated by Django 3.1.6 on 2021-03-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Information', '0003_auto_20210318_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='link',
            field=models.URLField(blank=True, default='', verbose_name='optional link'),
        ),
    ]
