# Generated by Django 3.1.6 on 2021-03-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Information', '0005_event_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='location'),
        ),
    ]
