# Generated by Django 3.1.6 on 2021-03-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Information', '0006_auto_20210323_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(verbose_name='end date/time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='link',
            field=models.URLField(blank=True, default='', verbose_name='link (optional)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(verbose_name='start date/time'),
        ),
    ]
