# Generated by Django 3.1.7 on 2021-04-08 20:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Information', '0007_auto_20210323_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='event description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.TimeField(verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.TimeField(verbose_name='start time'),
        ),
    ]
