# Generated by Django 3.1.7 on 2021-04-08 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Information', '0008_auto_20210408_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end',
            new_name='endtime',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start',
            new_name='starttime',
        ),
    ]
